name: Automate Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: app-hyrax-customers@

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Trigger Deployment Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = [
              "beta-auto-deploy.yaml",
              "demo-auto-deploy.yaml",
              "staging-auto-deploy.yaml",
              "prod-auto-deploy.yaml",
              "nightly-auto-deploy.yaml"
            ];

            for (const workflow of workflows) {
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: [
                  "beta-auto-deploy.yaml",
                  "demo-auto-deploy.yaml",
                  "staging-auto-deploy.yaml",
                  "prod-auto-deploy.yaml",
                  "nightly-auto-deploy.yaml"
                ],
                ref: '${{ steps.tag_version.outputs.new_tag }}',
              });
              console.log(`Triggered ${workflow}`);
            }
